apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-engineer-cloud-hotanphat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-engineer-cloud-hotanphat
  template:
    metadata:
      labels:
        app: capstone-engineer-cloud-hotanphat
    spec:
      containers:
        - name: capstone-engineer-cloud-hotanphat
          image: your-image:tag
          ports:
            - containerPort: 80
