apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-phat
  labels:
    app: final-project-phat
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: final-project-phat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: final-project-phat
    spec:
      containers:
        - image: phat99/final-project-phat
          imagePullPolicy: Always
          name: final-project-phat
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: final-project-phat
  labels:
    app: final-project-phat
spec:
  type: LoadBalancer
  selector:
    app: final-project-phat
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
