apiVersion: v1
clusters:
  - cluster:
      server: <KUBERNETES_API_SERVER_URL>
      certificate-authority-data: <BASE64_ENCODED_CERTIFICATE_AUTHORITY_DATA>
    name: capstone-project-final
contexts:
  - context:
      cluster: capstone-project-final
      user: my-user
    name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
  - name: my-user
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        command: aws-iam-authenticator
        args:
          - "token"
          - "-i"
          - "capstone-project-final"
