version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint

      - run:
          name: Run Lint
          command: |
            hadolint Dockerfile
      # Install AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            pip install awscli --upgrade --user

      # Authenticate with AWS ECR
      - run:
          name: Authenticate with AWS ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
      # Install Docker client
      - run:
          name: Install Docker client
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

      # Start Docker service
      - run:
          name: Start Docker service
          command: service docker start

      # Set up remote Docker environment
      - setup_remote_docker:
          version: 20.10.9
      # Build and push Docker image to ECR
      - run:
          name: Build and push Docker image to ECR
          command: |
            docker build -t final-project .
            docker tag final-project:latest $AWS_ECR_URL/final-project:latest
            docker push $AWS_ECR_URL/final-project:latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
