version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            pip install awscli --upgrade --user

      - run:
          name: Configure AWS credentials
          command: |
            echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> $BASH_ENV
            echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> $BASH_ENV
            echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $BASH_ENV

      - run:
          name: Install kubectl
          command: |
            sudo apt-get update && sudo apt-get install -y apt-transport-https
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl

      - run:
          name: Deploy CloudFormation stack
          command: |

            aws cloudformation deploy --stack-name capstone-project-final --template-file cloudformation/cloudformation.yml --parameter-overrides ID=123 --capabilities CAPABILITY_IAM

            aws cloudformation wait stack-create-complete --stack-name capstone-project-final

      - run:
          name: Configure kubectl
          command: |
            mkdir -p ${HOME}/.kube
            echo "$KUBECONFIG_CONTENT" | base64 -d > ${HOME}/.kube/config

      - run:
          name: Deploy Kubernetes resources
          command: |
            kubectl proxy --port=8080
            kubectl apply -f deployments/deployments.yml 
            kubectl rollout status deployment/capstone-engineer-cloud-hotanphat --timeout=1200s

      - persist_to_workspace:
          root: .
          paths:
            - src/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
