version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      - run:
          name: Install AWS CLI
          command: |
            pip install awscli --upgrade --user

      - run:
          name: Configure AWS credentials
          command: |
            echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID >> $BASH_ENV
            echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY >> $BASH_ENV
            echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION >> $BASH_ENV

      - run:
          name: Deploy CloudFormation stack
          command: |

            aws cloudformation deploy --stack-name capstone-project-final --template-file cloudformation/cloudformation.yml --parameter-overrides ID=123 --capabilities CAPABILITY_IAM

            aws cloudformation wait stack-create-complete --stack-name capstone-project-final

      - run:
          name: Configure kubeconfig
          command: |
            mkdir ~/.kube
            aws eks update-kubeconfig --region $AWS_DEFAULT_REGION --name capstone-project-final --kubeconfig ~/.kube/config

      - run:
          name: Deploy Kubernetes resources
          command: |
            kubectl apply -f deployments/deployments.yml --record

      - persist_to_workspace:
          root: .
          paths:
            - src/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
