version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.3
  aws-ecr: circleci/aws-ecr@3.1.0

jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:13.8.0

    steps:
      - checkout

      # Step 1: Linting
      - run:
          name: install dependencies
          command: |
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: Run Lint
          command: |
            hadolint Dockerfile
      - setup_remote_docker:
          version: 20.10.7
      # Step 2: Build Docker Image
      - run:
          name: Build Docker Image
          command: |
            export TAG=v${CIRCLE_BUILD_NUM}
            export IMAGE_NAME=capstone-project-final

            docker build -t phat99/$IMAGE_NAME:$TAG .

      # Step 3: Blue/Green Deployment
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: capstone-project-final
          install-kubectl: true
          aws-region: $AWS_DEFAULT_REGION

      - run:
          name: Install AWS IAM Authenticator
          command: |
            if which aws-iam-authenticator > /dev/null; then
              echo "AWS IAM Authenticator for Kubernetes is already installed"
              exit 0
            fi

            PLATFORM="linux"
            if [ -n "$(uname | grep "Darwin")" ]; then
              PLATFORM="darwin"
            fi

            RELEASE_TAG=""
            RELEASE_URL="https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/latest"

            if [ -n "${RELEASE_TAG}" ]; then
              RELEASE_URL="https://api.github.com/repos/kubernetes-sigs/aws-iam-authenticator/releases/tags/${RELEASE_TAG}"
            fi

            DOWNLOAD_URL=$(curl -s --retry 5 "${RELEASE_URL}" \
                | grep "${PLATFORM}" | awk '/browser_download_url/ {print $2}' | sed 's/"//g')

            DOWNLOAD_URL=$(echo "${DOWNLOAD_URL}" | tr -d '\r')

            curl -L -o aws-iam-authenticator "$DOWNLOAD_URL"

            chmod +x ./aws-iam-authenticator

            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi

            $SUDO mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator

      - run:
          name: Apply Kubernetes Deployment
          command: |
            kubectl apply -f deployments/deployments.yml --record
            kubectl rollout status deployment/your-deployment-name

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
